package com.techelevator.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.sql.Timestamp;
import java.util.List;

public class WorkOrder {
    @JsonProperty("id")
    int orderId;
    int submitterId;
    @JsonProperty("unit")
    int unitNumber;
    @JsonProperty("area")
    String areaName;
    @JsonProperty("status")
    String statusName;
    @JsonProperty("description")
    String orderDescription;
    Timestamp whenPosted;
    @JsonProperty("emergency")
    boolean isEmergency;
    int rating;
    @JsonProperty("comments")
    List<Comment> orderComments;
    @JsonProperty("images")
    List<String> images;

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }

    public WorkOrder() {
    }

    // orderId auto-generated by database
    // statusName set to "Open" by default in DAO
    // whenPosted timestamp auto-generated by database
    // rating not included when first creating new WorkOrder object based on user stories
    // orderComments is empty when new WorkOrder object is first created
    public WorkOrder(int submitterId, int unitNumber, String areaName, String orderDescription, boolean isEmergency) {
        this.submitterId = submitterId;
        this.unitNumber = unitNumber;
        this.areaName = areaName;
        this.orderDescription = orderDescription;
        this.isEmergency = isEmergency;
    }

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getSubmitterId() {
        return submitterId;
    }

    public void setSubmitterId(int submitterId) {
        this.submitterId = submitterId;
    }

    public int getUnitNumber() {
        return unitNumber;
    }

    public void setUnitNumber(int unitNumber) {
        this.unitNumber = unitNumber;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    public String getOrderDescription() {
        return orderDescription;
    }

    public void setOrderDescription(String orderDescription) {
        this.orderDescription = orderDescription;
    }

    public Timestamp getWhenPosted() {
        return whenPosted;
    }

    public void setWhenPosted(Timestamp whenPosted) {
        this.whenPosted = whenPosted;
    }

    public boolean isEmergency() {
        return isEmergency;
    }

    public void setEmergency(boolean emergency) {
        isEmergency = emergency;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public List<Comment> getOrderComments() {
        return orderComments;
    }

    public void setOrderComments(List<Comment> orderComments) {
        this.orderComments = orderComments;
    }
}
